name: Github Actions demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Started"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: "Installation"
        run: "npm i"
      - name: "Build"
        run: "npm run build"
# FIREBASE_SERVICE_ACCOUNT_GITHUB_ACTIONS_DEMO_1A459